name: Michael Griffith
favicon: null
layout_spectrum: 0.29186076973564923
typography_spectrum: 1
title: "They say I'm apathetic, but I just don't care."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0072d1'
    - '#ff8500'
    - '#ababab'
    - '#ffbe78'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
