name: Michael Griffith
favicon: null
layout_spectrum: 0.29186076973564923
typography_spectrum: 1
title: "Michael Griffith's Corner of the World"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#767676'
    - '#4f4f4f'
    - '#fefefe'
    - '#a0a0a0'
  brandStrength: 0.7314360740128905
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.9554073209874332
purpose: []
